accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
]

ajax/urls.py
from django.contrib import admin
from django.urls import path, include
from posts.views import PostList
urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('',PostList.as_view(),name='home'),
    path('accounts/', include('accounts.urls'))
]

posts/urls.py
from django.urls import path
from . import views

app_name='posts'
urlpatterns = [
    path('',views.PostList.as_view(),name='list'),
    path('create/',views.PostCreate.as_view(),name='create'),
    path('<pk>/',views.PostDetail.as_view(),name='detail'),
    path('<int:pk>/comments',views.CommentCreate.as_view(),name="comment_create"),
    path('<int:pk>/like/', views.like ,name='like'),
]

accounts/models.py
from django.db import models

# Create your models here.

posts/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=1)
    created_at = models.DateTimeField(auto_now=True)
    like = models.ManyToManyField(settings.AUTH_USER_MODEL,related_name='like_users',blank=True)
    
    def __str__(self):
        return self.title
        
    def get_absolute_url(self):
        return reverse('posts:detail', kwargs={'pk': self.pk})
        
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=1)
    content = models.TextField()

    def __str__(self):
        return self.content
        
    def get_absolute_url(self):
        return reverse('posts:detail', kwargs={'pk': self.post_id})

posts/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    content = forms.CharField(label='Comment')

    class Meta:
        model = Comment
        fields = ['content',]

accounts/views.py
from django.shortcuts import render

# Create your views here.

posts/views.py
from django.shortcuts import render,get_object_or_404, resolve_url, redirect
from django.views.generic import ListView, CreateView,DetailView
from .models import Post, Comment
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import CommentForm
from django.contrib.auth.decorators import login_required
import json
from django.http import HttpResponse

# Create your views here.

class PostList(ListView):
    model = Post
    
class PostCreate(LoginRequiredMixin,CreateView):
    model = Post
    fields = ['title','content',]

class PostDetail(DetailView):
    model = Post
    
    def get_object(self):
        post = Post.objects.prefetch_related('comment_set__user').select_related('user')
        return get_object_or_404(post, pk=self.kwargs.get('pk'))
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = CommentForm()
        return context
        
class CommentCreate(LoginRequiredMixin, CreateView):
    model = Comment
    fields = ['content',]
    
    def form_valid(self,form):
        post = Post.objects.get(id = self.kwargs.get('pk'))
        self.object = form.save(commit=False)
        self.object.post = post
        self.object.user = self.request.user
        self.object.save()
        
        return super().form_valid(form)

# 로그인했니??
@login_required
def like(request,pk):
    if request.is_ajax():
        user = request.user
        post = Post.objects.get(pk=pk)
        
        # 사용자가 like를 눌렀으면 취소
        if post.like.filter(id=user.id).exists():
            post.like.remove(user)
        # 안눌렀으면 좋아요
        else:
            post.like.add(user)
        data = {'likes_count' : post.like.count()}
        return HttpResponse(json.dumps(data), content_type="application/json")
        
    else:
        return redirect( resolve_url('posts:detail',pk) )

accounts/templates/accounts/login.html
{%extends 'base.html'%}
{% load bootstrap4 %}
{%block body%}
    <form method='post'>
        {%csrf_token%}
        {% bootstrap_form form %}
        <input type="submit" value="Submit"/>
    </form>
{%endblock%}

posts/templates/posts/_post.html
<div class="col-sm">
  <div class="card" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title">{{post.title}}</h5>
      <a href="{% url 'posts:detail' post.id %}" class="btn btn-primary">글보기</a>
    </div>
  </div>
</div>

posts/templates/posts/post_detail.html
{%extends 'base.html'%}
{% load bootstrap4 %}

{%block body%}
    <div class="jumbotron">
      <h1 class="display-4">{{post.title}}</h1>
      <p class="lead">{{post.created_at}}</p>
      <hr class="my-4">
      <p>{{post.content}}</p>
      <a class="btn btn-primary btn-lg" href="#" role="button">기능없는버튼</a>
      <p>{{post.like.all}}</p>
      {%if user in post.like.all %}
        <button id="like" class="btn btn-primary" name="{{post.id}}"> <i id="heart" class="fas fa-heart"><span id="like_count" class="badge badge-light">{{post.like.count}}</span> </i> </button>
      {%else%}
        <button id="like" class="btn btn-primary" name="{{post.id}}"> <i id="heart" class="far fa-heart"><span id="like_count" class="badge badge-light">{{post.like.count}}</span></i> </button>
      {%endif%}
    </div>
    
    <form action="{% url 'posts:comment_create' post.id %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-primary">
    </form>
    
    {% for comment in post.comment_set.all %}
        <div class="card">
          <div class="card-body">
            {{comment.user.username}} : {{comment.content}}
          </div>
        </div>
    {% endfor %}
    
    <script type="text/javascript">
      $('#like').click(function(){
        var pk = $(this).attr('name')
        $.ajax({
          type: "POST",
          url: "{% url 'posts:like' post.id %}",
          data: {'pk':pk, 'csrfmiddlewaretoken':'{{csrf_token}}'},
          dataType: 'json',
          
          success: function(data){
            $('#like_count').text(data.likes_count)
            
            if(   $('#heart').hasClass('fas')    ){
              $('#heart').removeClass('fas').addClass('far')
            }
            else{
              $('#heart').removeClass('far').addClass('fas')
            }
          },
          error: function(){
            
          }
          
        })
      })
      
    </script>
    
    
{%endblock%}

posts/templates/posts/post_form.html
{%extends 'base.html'%}

{%block body%}
    <form method='post'>
        {%csrf_token%}
        {{form.as_p}}
        <input type="submit" value="Submit"/>
    </form>
{%endblock%}

posts/templates/posts/post_list.html
{% extends 'base.html' %}

{% block body %}
    <div class="row">
    {% for post in post_list %}
        {% include 'posts/_post.html'%}
    {% endfor %}
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <script
      src="https://code.jquery.com/jquery-3.3.1.js"
      integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
      crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{%url 'home'%}">Home</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-item nav-link" href="{%url 'posts:create'%}">글작성</a>
            {% if user.is_authenticated == False %}
                <a class="nav-item nav-link" href="{%url 'accounts:login'%}">로그인</a>
            {% else %}
                <a class="nav-item nav-link" href="{%url 'accounts:logout'%}">로그아웃</a>
                <h4>{{user.username}}</h4>
            {% endif %}
          
        </div>
      </div>
    </nav>
    <div class="container">
    {% block body %}
    {% endblock %}
    </div>
    <!--<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>